export default{
    ci:{
        prefix:'',
        suffix:''
    },
    dev:{
        admin_api:'https://ojaryxuxdh.execute-api.us-east-1.amazonaws.com',
        home:'https://dev.publicgrid.energy',
        tanstack:'https://tanstack-dev.onepublicgrid.com',
        pg_admin:'https://dev.publicgrid.co',
        api_v2:'https://api-dev.publicgrd.com/v2',
    },
    staging:{
        admin_api:'',
        home:'https://staging.publicgrid.energy',
        pg_admin:'https://staging.publicgrid.co',
        api_v2:'https://api-staging.publicgrd.com/v2',
    },
    prod:{
        admin_api:'https://perzebrgr8.execute-api.us-east-1.amazonaws.com',
        home:'https://publicgrid.energy',
        pg_admin:'https://publicgrid.co',
        api_v2:'https://api.onepublicgrid.com/v2',
    },
};