export default{
    ci:{
        prefix:'',
        suffix:''
    },
    dev:{
        admin_api:'https://ojaryxuxdh.execute-api.us-east-1.amazonaws.com',
        home:'https://dev.publicgrid.energy',
        pg_admin:'https://dev.publicgrid.co',
    },
    staging:{
        admin_api:'',
        home:'https://staging.publicgrid.energy',
        pg_admin:'https://staging.publicgrid.co',
    },
    prod:{
        admin_api:'https://perzebrgr8.execute-api.us-east-1.amazonaws.com',
        home:'https://publicgrid.energy',
        pg_admin:'https://publicgrid.co',
    },
};